/*--------------------------------------------------------------------------
 * This file is autogenerated from pidx_config.h.in 
 * during the cmake configuration of your project. If you need to make changes
 * edit the original file NOT THIS FILE.
 * --------------------------------------------------------------------------*/

#ifndef _PIDX_CONFIG_H_
#define _PIDX_CONFIG_H_

#define PIDX_GIT_REVISION "9cf20791d8fec83d93a29900dfcf17adcf75aa95"

#define PIDX_MAX_DIMENSIONS 5

#define BUILD_SHARED_LIBS 0
#define PIDX_HAVE_MPI 1
#define PIDX_HAVE_ZFP 0
#define PIDX_OPTION_PNETCDF 0
#define PIDX_OPTION_HDF5 1

//ACTIVE_TARGET is defined by MPI, but we may want to override it for specific configs
//NOTE: disable for shaheen (how should we control machine-specific settings like this?)
//NOTE: we want locks, not fences (ACTIVE_TARGET = 0) on ash (CHPC).
#define PIDX_ACTIVE_TARGET ACTIVE_TARGET
#undef PIDX_ACTIVE_TARGET

#endif //_PIDX_CONFIG_H_
