/*--------------------------------------------------------------------------
 * This file is autogenerated from pidx_config.h.in 
 * during the cmake configuration of your project. If you need to make changes
 * edit the original file NOT THIS FILE.
 * --------------------------------------------------------------------------*/

#ifndef _PIDX_CONFIG_H_
#define _PIDX_CONFIG_H_

#define PIDX_GIT_REVISION "df34739824ec64ceed36800c13d8b14ee455f9d6"

#define PIDX_MAX_DIMENSIONS 5

#define BUILD_SHARED_LIBS 0
#define PIDX_HAVE_MPI 1
#define PIDX_OPTION_PNETCDF 0
#define PIDX_OPTION_HDF5 0

#undef PIDX_HAVE_ZFP

//#define PIDX_ACTIVE_TARGET 1

#endif //_PIDX_CONFIG_H_
